### ISSUE TITLE
Quality: Code Documentation

### ISSUE THREAD

**Issue by dmzoneill** [jaggedsoft/php-binance-api#90]
Provide API documentation using doxygen, for download or other use
Update php code for documentation purposes

**Tasks:**
- [x] Setup branch gh-pages for html documentation 
- [x] Setup travis with doxygen to build output and push to branch
- [x] Update PHP code with [PHPDOC](http://manual.phpdoc.org/HTMLframesConverter/default/)
- [x] Add link to zip file to main page 
- [x] Add markdown output for use on github wiki page or README-api.md - [markdown](https://www.stack.nl/~dimitri/doxygen/manual/markdown.html)

**Comment by dmzoneill** [comment]
closing for now, work needed for websockets
